### ISSUE TITLE
Map Interfaces Todo List

### ISSUE THREAD

**Issue by ngottlieb** [AmericanWhitewater/wh2o-vue#23]
- [ ]  hide rapids for non-active river on detail page
- [ ]  refactor detail map rapid display to use existing `<rapid-item>` component
- [ ]  fix national map so that it doesn't show an error when you're zoomed out ("zoom in to see rivers in the table" CTA)
- [ ] fix mouseover on national map to highlight/scroll to reach in question on table
- [ ] fix scrollbars on national map table
- [ ] hook up search on national map table
- [ ] reinstate satellite / topo toggle on national and detail maps
